js_meme:
    resource: "@JSMemeBundle/Resources/config/routing.yml"
    prefix:   /

js_user:
    resource: "@JSUserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation


#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

fos_user_profile_edit:
    path: /profile/edit
    methods: [get, post]
    defaults:
        _controller: FOSUserBundle:Profile:edit

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin